name: mercari_demo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share: ^2.0.0

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  flutterflow_ui: ^0.2.0+1
  photo_manager: ^2.5.0 
  permission_handler: ^10.0.0
  path_provider: ^2.0.15 

  http: any
  share: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/shoes.jpg
    - assets/cloth.jpg
    - assets/electronics.jpg
    - assets/back.jpg
    - assets/cameraroll/shoes.jpg
    - assets/cameraroll/cloth.jpg
    - assets/cameraroll/electronics.jpg